name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            stadgent/probe-sparql-mono:latest
            stadgent/probe-sparql-mono:${{ github.sha }}
          cache-from: type=registry,ref=stadgent/probe-sparql-mono:latest
          cache-to: type=inline
